name: DELETER
on:
  workflow_dispatch:
jobs:
  ProsesBackup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Menginstall Rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Memuat konfigurasi Rclone
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.ssh }}
        EOF
    - name: DELETE 1
      run: |
         rclone delete "ssh1:" --drive-use-trash=false
    - name: DELETE 2
      run: |
         rclone delete "ssh2:" --drive-use-trash=false
#    - name: DELETE 3
#      run: |
#         rclone delete "ssh3:" --drive-use-trash=false
    - name: DELETE 4
      run: |
         rclone delete "ssh4:" --drive-use-trash=false
    - name: DELETE 6
      run: |
         rclone delete "ssh6:" --drive-use-trash=false
    - name: DELETE 7
      run: |
         rclone delete "ssh7:" --drive-use-trash=false
    - name: DELETE 8
      run: |
         rclone delete "ssh8:" --drive-use-trash=false
    - name: DELETE 9
      run: |
         rclone delete "ssh9:" --drive-use-trash=false
    - name: DELETE 10
      run: |
         rclone delete "ssh10:" --drive-use-trash=false
    - name: DELETE 11
      run: |
         rclone delete "ssh11:" --drive-use-trash=false
    - name: DELETE 12
      run: |
         rclone delete "ssh12:" --drive-use-trash=false
    - name: DELETE 13
      run: |
         rclone delete "ssh13:" --drive-use-trash=false
    - name: DELETE 14
      run: |
         rclone delete "ssh14:" --drive-use-trash=false
    - name: DELETE 15
      run: |
         rclone delete "ssh15:" --drive-use-trash=false
    - name: DELETE 16
      run: |
         rclone delete "ssh16:" --drive-use-trash=false
    - name: DELETE 17
      run: |
         rclone delete "ssh17:" --drive-use-trash=false
    - name: DELETE 18
      run: |
         rclone delete "ssh18:" --drive-use-trash=false
    - name: DELETE 19
      run: |
         rclone delete "ssh19:" --drive-use-trash=false
    - name: DELETE 20
      run: |
         rclone delete "ssh20:" --drive-use-trash=false
    - name: DELETE 21
      run: |
         rclone delete "ssh21:" --drive-use-trash=false
    - name: DELETE 22
      run: |
         rclone delete "ssh22:" --drive-use-trash=false
    - name: DELETE 23
      run: |
         rclone delete "ssh23:" --drive-use-trash=false
    - name: DELETE 24
      run: |
         rclone delete "ssh24:" --drive-use-trash=false
    - name: DELETE 25
      run: |
         rclone delete "ssh25:" --drive-use-trash=false
    - name: DELETE 26
      run: |
         rclone delete "ssh26:" --drive-use-trash=false
    - name: DELETE 27
      run: |
         rclone delete "ssh27:" --drive-use-trash=false
    - name: DELETE 28
      run: |
         rclone delete "ssh28:" --drive-use-trash=false
    - name: DELETE 29
      run: |
         rclone delete "ssh29:" --drive-use-trash=false
    - name: DELETE 30
      run: |
         rclone delete "ssh30:" --drive-use-trash=false
    - name: DELETE 31
      run: |
         rclone delete "ssh31:" --drive-use-trash=false
    - name: DELETE 32
      run: |
         rclone delete "ssh32:" --drive-use-trash=false
    - name: DELETE 33
      run: |
         rclone delete "ssh33:" --drive-use-trash=false && rclone delete "ssh34:" --drive-use-trash=false && rclone delete "ssh35:" --drive-use-trash=false && rclone delete "ssh36:" --drive-use-trash=false && rclone delete "ssh37:" --drive-use-trash=false && rclone delete "ssh38:" --drive-use-trash=false && rclone delete "ssh39:" --drive-use-trash=false
