name: SumberBaru
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
jobs:
  ProsesBackup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Menginstall Rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Memuat konfigurasi Rclone
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.baru }}
        EOF
#    - name: Cleaning 0
#      run: |
#         rclone delete "del:" --drive-use-trash=false
    - name: Penyalinan 1
      run: |
         rclone S1: D1: --drive-server-side-across-configs --max-age 24h --ignore-errors
    - name: Penyalinan 2
      run: |
         rclone copy S2: D2: --drive-server-side-across-configs --max-age 24h --ignore-errors
